//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Link_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryLanguage
    {
        public string CountryCode { get; set; }
        public string Language { get; set; }
        public int IsOfficial { get; set; }
        public double Percentage { get; set; }
    }
}
